version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: cocomarket
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST:
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  spring-app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql

