version: '3'
services:
  coco:
    image: oumaima55/imagebackendoumaima:latest
    restart: on-failure
    ports:
      - '8088:8088'
    depends_on:
      - mysql
    networks:
      - mynetwork
    volumes:
      - .m2:/root/.m2
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: oumaima
      MYSQL_DATABASE: cocomarket
      MYSQL_USER: oumaima
      MYSQL_PASSWORD: oumaima
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  mynetwork:
volumes:
  mysql-data:
  .m2:

