version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: CoCoMarket
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - spring-network

  backend:
    image: samibenlakhal/backendimage
    ports:
      - "8088:8088"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/CoCoMarket?createDatabaseIfNotExist=true
    volumes:
      - spring_data:/app/data
    depends_on:
      - mysql
    networks:
      - spring-network

  frontend:
    image: samibenlakhal/frontendimage
    ports:
      - "4200:80"
    volumes:
      - angular_data:/app/data
    networks:
      - spring-network

networks:
  backend-network:
    driver: bridge
volumes:
  angular_data:
  mysql_data:
  mysql_config:
  spring_data: